version: '2.0'
services:
  weather:
    build:
      context: .
      dockerfile: TanksSimulator.WeatherApi/Dockerfile
    ports:
    - "8001:80"
    networks:
    - tanks-network  
  data:
    build: 
      context: .
      dockerfile: TanksSimulator.DataApi/Dockerfile
    ports:
    - "8002:80"
    networks:
    - tanks-network  
  results:
    build: 
      context: .
      dockerfile: TanksSimulator.ResultsApi/Dockerfile
    ports:
    - "8003:80"
    networks:
    - tanks-network
  web:
    build: 
      context: .
      dockerfile: TanksSimulator.WebApi/Dockerfile
    ports:
    - "8080:80"
    - "8081:8001"
    - "8082:8002"
    - "8083:8003"
    networks:
    - tanks-network
    environment:
    - WEATHER_API_URL=http://weather:8081
    - DATA_API_URL=http://data:8082
    - RESULT_API_URL=http://results:8083

networks:
  tanks-network:
    external: true