version: '2.0'
services:
  web:
    build: 
      context: .
      dockerfile: TanksSimulator.WebApi/Dockerfile
    ports:
    - "80:80"
  weather:
    build:
      context: .
      dockerfile: TanksSimulator.WeatherApi/Dockerfile
    ports:
    - "80:8000"
  data:
    build: 
      context: .
      dockerifle: TanksSimulator.DataApi/Dockerfile
    ports:
    - "80:8001"
  results:
    build: 
      context: .
      dockerfile: TanksSimulator.ResultsApi/Dockerfile
    ports:
    - "80:8002"